[package]
name = "permrs"
version = "0.1.0"
authors = ["Alessandro Toia <gort818@gmail.com>"]
edition = "2018"

[dependencies]
clap =  {version ="3.2.6", features = ["yaml"]}
xdg = "2.4.1"
run_script = "0.9.0"
walkdir = "2.3.2"
dirs = "4.0.0"
